spring:
  profiles:
    active: #spring.profiles.active#
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/sc_flowable?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hhh123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
flowable:
#关闭定时任务JOB
  async-executor-activate: false

#####最新在用应用
server:
  port: 8080
    #自动部署文件路径后缀
#   process-definition-location-prefix: classpath:/processes/
#   process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml